pipeline:
  agent:
    any:
  stages:
    - stage: "Checkout"
      steps:
        - git "https://github.com/mudaliar20/PowerTrain.git"
    - stage: "Deploy to GKE"
      steps:
        - "sh 'gcloud auth list'"
        - "sh 'gcloud container clusters get-credentials dcp-gke --region us-east1 --project ford-project-319713'"
        - "sh 'kubectl apply -f gke-deployment.yaml'"
